typography_spectrum: 0.63021703180857
content_rating:
  adult: false
color:
  brandStrength: 0.8332335494924337
  lightness: 0.1558560417033732
  saturation: 0.26371971890330315
  rhythmicContrast: 0.8721363786607981
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
layout_spectrum: 0.3688692811410874
author:
  name: greg Wolfe
  email: gw@tripleluxe.com
name: GREG WOLFE
title: Producer/Songwriter/Guitarist/Lover/Global Thinker
description: 'Breathe In, Breathe Out.'
